version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: "always"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  config-server:
    ports:
      - 8888:8888
    build:
      context: ./config-server
      dockerfile: Dockerfile

  task-executor-service:
    ports:
      - 7543:7543
    build:
      context: ./task-executor-service
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_POFILE=dockerCompose
    command: sh -c "sleep 10 && java -jar app.jar"
    depends_on:
      - config-server
      - rabbitmq

  task-manager-service:
    ports:
      - 7878:7878
    build:
      context: ./task-manager-service
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_POFILE=dockerCompose
    depends_on:
      - config-server
      - postgres
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
