server:
  port: 7543

spring:
  cloud:
    config:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  level:
    ROOT: INFO