server:
  port: 7543

spring:
  cloud:
    config:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

task-executor-service:
  listener:
    concurrent-consumers: 5
    max-concurrent-consumers: 10

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    logfile:
      external-file: /logs/application.log
    health:
      show-details: always
  security:
    enabled: false

logging:
  file:
    name: logs/application.log
  level:
    ROOT: INFO

---
spring:
  profiles: dockerCompose

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password