server:
  port: 7878

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  #    show-sql: true

  cloud:
    config:
      enabled: false

task-manager-service:
  messaging:
    timeout: 50000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    logfile:
      external-file: /logs/application.log
    health:
      show-details: always
  security:
    enabled: false

logging:
  file:
    name: logs/application.log
  level:
    ROOT: INFO

---
spring:
  profiles: inMemory
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
      schema-locations: classpath:H2Schema.sql
---
spring:
  profiles: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      schema-locations: classpath:PostgresSchema.sql
---
spring:
  profiles: dockerCompose
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/db
    username: postgres
    password: postgres

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password

  sql:
    init:
      mode: always
      schema-locations: classpath:PostgresSchema.sql