DROP TABLE IF EXISTS TASKS CASCADE;
CREATE TABLE TASKS
(
    ID     BIGSERIAL    NOT NULL PRIMARY KEY,
    VALUE  INT          NOT NULL,
    TYPE   VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);